business/urls.py
from django.conf.urls import url
from . import views

app_name = "business"


urlpatterns = [
    url('^$' , views.business , name = 'business'),
]

discover/urls.py
from django.conf.urls import url
from . import views

app_name = "discover"


urlpatterns = [
    url('^$' , views.discover , name = 'discover'),
]

groups/urls.py
from django.conf.urls import url
from . import views

app_name = "groups"


urlpatterns = [
    url('^$' , views.groups , name = 'groups'),
]

home/urls.py
from django.conf.urls import url ,include
from . import views

app_name = "home"

urlpatterns = [
    url("" , views.home , name = "home"),
]

login/urls.py
from django.conf.urls import url
from . import views

app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
]

notifications/urls.py
from django.conf.urls import url
from . import views

app_name = "notifications"


urlpatterns = [
    url('^$' , views.notifications , name = 'notifications'),
]

settings/urls.py
from django.conf.urls import url
from . import views

app_name = "settings"


urlpatterns = [
    url('^$' , views.settings , name = 'settings'),
]

signup/urls.py
from django.conf.urls import url
from . import views

app_name = "signup"


urlpatterns = [
    url('^$' , views.signup , name = 'signup'),
]

uprofile/urls.py
from django.conf.urls import url
from . import views

app_name = "profile"


urlpatterns = [
    url('^$' , views.profile , name = 'profile'),
]

vibes/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$' , include('home.urls')),
    url('^login/' , include('login.urls')),
    url('^business/' , include('business.urls')),
    url('^discover/' , include('discover.urls')),
    url('^groups/' , include('groups.urls')),
    url('^messages/' , include('vmessages.urls')),
    url('^notifications/' , include('notifications.urls')),
    url('^settings/' , include('settings.urls')),
    url('^signup/' , include('signup.urls')),
    url('^profile/' , include('uprofile.urls')),
]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

vmessages/urls.py
from django.conf.urls import url
from . import views

app_name = "messaging"


urlpatterns = [
    url('^$' , views.messaging , name = 'messaging'),
]

business/models.py
from django.db import models

# Create your models here.


class sell_goods(models.Model):
    itemid = models.AutoField(primary_key = True)
    itemdesc = models.CharField(max_length = 255 )
    price = models.FloatField(max_length = 10)
    itemimg = models.FileField()

home/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models

# Create your models here.
class signup(models.Model):
    pass

    class Meta:
        db_table = "signup"

business/forms.py
from django import forms
from .models import sell_goods

class sell_frm(forms.ModelForm):
    class Meta:
        model = sell_goods
        fields = ('itemdesc','price' , 'itemimg')

        widgets = {
            'itemdesc':forms.Textarea(attrs = {'rows':4 , 'cols':30 , 'name':'description'}),
        }

business/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import sell_frm



def business(request):
    form = sell_frm()
    if request.method =='POST':
        return render(request , "business/business.html" , context = {"form":form})

    else:
        return render(request , "business/business.html" , context = {"form":form})

discover/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.



def discover(request):
    return render(request , "discover/discover.html")

groups/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def groups(request):
    return HttpResponse("Hello groups")

home/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request , "home/home.html")

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.



def login(request):
    return render(request , "login/login.html")


def forgotcredetials(request):
    return render(request , "login/forgot.html")

notifications/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def notifications(request):
    return HttpResponse("Hello notifs")

settings/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.



def settings(request):
    return HttpResponse("Hello settings")

signup/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def signup(request):
    return render(request , "signup/signup.html")

uprofile/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def profile(request):
    return render(request , "uprofile/uprofile.html")

vmessages/views.py
from django.shortcuts import render

from django.http import HttpResponse
# Create your views here.


def messaging(request):
    # return HttpResponse("Hello messages")
    return render(request , "messages/messages.html" ,)

business/templates/business/business.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="icon" href="{% static 'business/img/vibes.jpg' %}" type="image/jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
     integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'business/business.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <meta charset="utf-8">
    <title>Vibes | Business</title>
  </head>
  <body>
    <div class="header">
        <div class="nav-bar">
              <div class="logo">
                  <img src="{% static 'business/img/vibes.jpg' %}" alt="">
              </div>

                <input type="text" name="search" value="" autocomplete="on" autofocus placeholder="Search">

              <a href="{% url 'home:home' %}">
                <span class="fa fa-home"></span>

              </a>

              <a href="#">
                <span class="fa fa-shopping-basket"></span>

              </a>

              <a href="#" class="hide-small">
                <span class="fa fa-line-chart"></span>

              </a>

              <a href="#" class="hide-small">
                <span class="fa fa-pencil"></span>

              </a>
              <a href="{% url 'discover:discover' %}" class="hide-small">
                <span class="fa fa-map-marker map"></span>

              </a>


              <a href="{% url 'groups:groups' %}">
                <span class="fa fa-users"></span>

              </a>

              <a href="{% url 'notifications:notifications' %}">
                <span class="fa fa-bell"></span>

              </a>


              <a href="#" class="hide-small">
                <span class="fa fa-calculator"></span>

              </a>

              <!-- <a href="{% url 'settings:settings' %}" class="hide-small">
                <span class="fa fa-cog"></span>

              </a> -->


        </div>

    </div>

    <div class="container">

        <div class="row">
          <div class="col-xs-12 col-sm-12 col-lg-7 col-xl-7">
                <div class="Goods">
                    <strong><label>Goods</label></strong>
                    <div class="stock">

                      <button type="button" name="button"><a href='#'>Buy</a></button>

                      <button type="button" name="button"><a href='#'>Order </a></button>
                    </div>

                    <div class="gen-good card">
                        <div class="good-img">
                            <div class="card-body">

                              <div class="container">

                                <div class="row">
                                  <div class="col-md-6 col-sm-12 col-xs-12 col-lg-6">
                                    <img src="{% static './business/img/robot.jpg' %}" class="card-img-right" alt="Hello world">
                                  </div>

                                  <div class="col-md-6 col-sm-12 col-xs-12 col-lg-6">
                                    <h1 class="card-title">Robot</h1>
                                    <p class="card-text">Robot on sell at 10$
                                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                    </p>

                                    <!-- Use ajax to submit the item for record keeping in sessions -->
                                    <div class="container">
                                      <div class="row">
                                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                          <label class="fa fa-map-marker map"></label>
                                          <label id="location">Multimedia</label>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                            <label class="item-price">Price: 10$</label>
                                        </div>

                                      </div>
                                    </div>
                                    <form class="addingcart" action="" method="post">
                                      {% csrf_token %}
                                      <!-- Add the item id on the hidden field -->
                                      <input type="hidden" name="itemid" value="">
                                      <input type="checkbox" name="picked" id="addcart">
                                      <label>Add to cart</label>
                                    </form>
                                  </div>


                                </div>
                              </div>


                            </div>

                          </div>
                    </div>
                    <div class="search-icon">
                      <a href="#" class="fa fa-search"></a>
                    </div>
                    <!-- end of card -->
                  </div>


            </div>

              <div class="col-xs-12 col-sm-12 col-lg-5 col-xl-5 sellingfrm">
                <div class="selling-stock">
                  <strong><label>Sell</label></strong>
                <form class="sell-good" action="" method="post">
                  {% csrf_token %}
                      {{form}}
                    <button name="submit" value="Sell" class="btn btn-info">Sell item</button>
                </form>
              </div>
              </div>


        </div>


        </div>

        <div class="lower-nav" id="lower-nav">

          <a href="#" class="hide-small">
            <span class="fa fa-line-chart"></span>
          </a>

          <a href="#" class="hide-small">
            <span class="fa fa-pencil"></span>
          </a>


            <a href="{% url 'discover:discover' %}" class="hide-small">
              <span class="fa fa-map-marker map"></span>
            </a>


          <a href="#" class="hide-small">
            <span class="fa fa-calculator"></span>
          </a>


          <form class="form horizontal-form form-search" action="#" method="get">
            <input type="text" name="search" value="" autocomplete="on" autofocus placeholder="Search">
            <input type="button" name="" value="Search" class="fa fa-link">
          </form>

        </div>

      <div class="footer">

      </div>
    </div>
  </body>
</html>

home/templates/home/Signup.html
<html >
<head>
	<title>Register</title>
	
	<link rel="stylesheet" href="styles.css"/>
	
</head>
<body>
	 <nav>
	 	
  <!---add other links here-->

  </nav>
	<div class="bon">
		<div class="bony">
			<form action="thanks.html" method="post">
			
				<h2>SignUp Today</h2>
				<input type="text" placeholder="Your full name" required>
				<input type="text" placeholder="Username" required>
				<input type="text"  placeholder="Eddress" required>
				<input type="password" placeholder="Password" required>
				<input type="password"  placeholder="confirm password" required>
				<input type="submit" value="signup">
				<p style="text-aligned:center">
					<span>Already have an account?</span><a class="link" href="login.html"><i ><b>Sign In</b></i></a>
				</p>
			
		
	</div>

</body>
<footer>
              <div class="row"><br><br>
                <div class="col-md-4">
                  <p>Contacts</p>
                  <p>Contacts</p>
                  <p>Contacts</p>
                  <p>Contacts</p>
                </div>
                <div class="col-md-4">
                  <p>Contacts</p>
                  <p>Contacts</p>
                  <p>Contacts</p>
                  <p>Contacts</p>
                 
                </div>
              </div>
            </footer>
</html>

home/templates/home/forgot.html
<html >

<head>
	<title>Forgot password</title>
	<link rel="stylesheet" href="style.css"/>
</head>
<body>
	<div class="bon">
		<div class="bony">
			<form action="recovery.html"
			<h3>please Enter your Email address.</h3>
			<input type="email" placeholder="Email Address"required  />

<input type="submit" value="submit" />

			
				
			</p>
		</div></div>

</body>
</html>

home/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Vibes | Home</title>
	<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
	 integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
	<link rel="stylesheet" href="{% static 'home/styles.css' %}">

	<link rel="icon" href="{% static 'business/img/vibes.jpg' %}" type="image/jpg">
</head>
<body>
	 <nav>

<!---add other links here-->

   <div class = "dropdown">
<button class = "dropbtn"> Account</button>
<div class="dropdown-menu">
	<a href="{% url 'login:login' %}">Login </a>
	<a href="{% url 'signup:signup' %}"> Sign Up </a>

</div>
</div>

  </nav>
  <div class = "LOGO">

  </div>
  <div class = "Desc">
  <p>
   <img src="{% static 'home/images/logo.jpg' %}" alt="image" id="photo">
</p>
<div class= "welcome">
	<h3>
		Welcome to vibes .
	</h3>
	<br>
	<br>
	</div>
	<div class="Search">
	 <input type="text" placeholder="Search on topics, find people and events" name="search" autocomplete="true">
	</div>

  <div class ="row">
  	<div class ="column">
  		<div class = "cardd"> <!--img src="public/images/image1.jpg" alt="image" id="profile" >--> <br>
  		Join Groups and engage in hottest topics around you<br>
  	<button class = "Learn"> Learn More</button>
</div>
  	</div>
	<div class ="row">
  	<div class ="column">
  		<div class = "cardd">  <!--img src="public/images/239.jpg" alt="image" id="profile" vibes>--> <br>
  		 You can buy quality products from people around you via vibes, the most effecial way to do small scale business<br>
  		<button class = "Learn"> Learn More</button>
</div>
  	</div>
  	<div class ="row">
  	<div class ="column">
  		<div class = "cardd">  <!--img src="public/images/pic.jpg" alt="image" id="profile" vibes>-->  <br>
  		  Locate People around and engage in general chats. To do it, you are recommended to turn allow vibes to access your location<br>
  		<button class = "Learn"> Learn More</button>
</div>
  	</div>
  	 <div class ="row">
  	<div class ="column">
  		<div class = "cardd">  <!--img src="public/images/a.jpg" alt="image" id="profile" vibes>--> <br>
  		 Find trending news,videos and events happenning right in your vicinity.<br><button class = "Learn"> Learn More</button>
 	 		</div>
  	</div>
</div>
		 <footer>
              <div class="container">
								<div class="row"><br><br>
									<div class="col-md-4">
										<p>Contacts</p>
										<p>Contacts</p>
										<p>Contacts</p>
										<p>Contacts</p>
									</div>
									<div class="col-md-4">
										<p>Contacts</p>
										<p>Contacts</p>
										<p>Contacts</p>
										<p>Contacts</p>

									</div>
								</div>
              </div>
    </footer>
	</body>
</html>

home/templates/home/login.html
<html >
<head>
	
	<title>login</title>
	<link rel="stylesheet" href="styles.css"/>
</head>



<body>
	<div class="bon">
		<div class="bony">

	<form action="welcome.html">

		<h3> Login Here</h3>

		<input type="text" placeholder="username" required/>

		<input type="password" placeholder="password" required/>
<p>
		<input type="checkbox"/><span>keep me sign in</span>

		<span class="forgot"><a href="Forgot.html"><i><b>forgot password?</b></i></a></span>

	</p>
		<input type="submit" value="login">

		<p style="text-align:center">
			<span>New member?</span><a class="link" href="Signup.html"><i><b>Signup</b></i></a>
		</p>
	</form>
	</div>
</div>

</body>
</html>

home/templates/home/recovery.html
<html >

<head>
	<title>Account Recovery</title>
	<link rel="stylesheet" href="style.css"/>
</head>
<body>
	<div class="bon">
		<div class="bony">
			<form action="recovery.html">
			<h3>Email verification link has been send.</h3>
			<p style="text-align: center" >We have send  verification link on your email addree please confirm your email address and login in to your account</p>

		
				<p style="text-align:center">Go back to  <a class="link" href="login.html"> <p align="center"><i><b>Login Page</b></i></a></p>


			
				
			</p>
		</div></div>

</body>
</html>

home/templates/home/thanks.html
<html >
<head>
	<meta charset="	UTF-8">
	
	<link rel="stylesheet" href="style.css"/>
</head>

<body>
	<div class="bon">
		<div class="bony">
			<h4>Thankyou for creating an account</h4>
			<p style="text-align: ">
				We have send  a verification link via your Email Address please confirm.
			</p>
			<p style="text-align:center";>
				<a href="login.html"><i><b>Sign In Now</b></i></a>

				</p>

</body>
</html>

home/templates/home/welcome.html
<html 
<head>
	<title></title>
	<link rel="stylesheet" href="style.css"/>
</head>
<body>
	<div class="bon"><div class="bony">
		<h3>Successful loged in</h3>
		<h3>Welcome back to Your Acount</h3>


		<p style="text-align:right;">
			<a class="link" href="login.html"><b>Logout</b></a>
		

</body>
</html>

signup/templates/signup/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block header %}

    {% endblock %}
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>


    {% block header %}

    {% endblock %}



    {% block content %}

    {% endblock %}


    {% block footer %}

    {% endblock %}

  </body>
</html>

signup/templates/signup/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Vibes | signup</title>
	<link rel="stylesheet" href="{% static 'signup/styles.css' %}"/>
</head>
<body>
	<p>
		<img src="{% static 'home/images/logo.jpg' %}" alt="image" id="photo">

	</p>

	<div class="bon">
		<div class="bony">
			<form action="{% url 'login:login' %}" method="post">

				<h2>Signup to vibes</h2>
				{% csrf_token %}
				<input type="text" placeholder="Your full name" required autocomplete="true" class="input">
				<input type="text" placeholder="Username" required autocomplete="true" class="input">
				<input type="email"  placeholder="email" required autocomplete="true" class="input">
				<input type="password" placeholder="Password" required  class="input">
				<input type="password" placeholder="confirm password" required class="input">
				<input type="submit" name="submit" value="signup" id="submit" class="input">

			</form>

				<p style="text-align:center">
					<span>Already have an account?</span>
						<a class="link" href="{% url 'login:login' %}">
						Sign in
					</a>
				</p>


	</div>
</div>

		<footer>

    </footer>
</body>
</html>

signup/templates/signup/signupme.html
{% extends 'base.html' %}


{% block content %}

{% endblock %}