business/urls.py
from django.conf.urls import url
from . import views

app_name = "business"


urlpatterns = [
    url('^$' , views.business , name = 'business'),
]

discover/urls.py
from django.conf.urls import url
from . import views

app_name = "discover"


urlpatterns = [
    url('^$' , views.discover , name = 'discover'),
]

groups/urls.py
from django.conf.urls import url
from . import views

app_name = "groups"


urlpatterns = [
    url('^$' , views.groups , name = 'groups'),
]

home/urls.py
from django.conf.urls import url ,include
from . import views

app_name = "home"

urlpatterns = [
    url("" , views.home , name = "home"),
]

login/urls.py
from django.conf.urls import url
from . import views

app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
]

notifications/urls.py
from django.conf.urls import url
from . import views

app_name = "notifications"


urlpatterns = [
    url('^$' , views.notifications , name = 'notifications'),
]

settings/urls.py
from django.conf.urls import url
from . import views

app_name = "settings"


urlpatterns = [
    url('^$' , views.settings , name = 'settings'),
]

signup/urls.py
from django.conf.urls import url
from . import views

app_name = "signup"


urlpatterns = [
    url('^$' , views.signup , name = 'signup'),
]

uprofile/urls.py
from django.conf.urls import url
from . import views

app_name = "profile"


urlpatterns = [
    url('^$' , views.profile , name = 'profile'),
]

vibes/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$' , include('home.urls')),
    url('^login/' , include('login.urls')),
    url('^business/' , include('business.urls')),
    url('^discover/' , include('discover.urls')),
    url('^groups/' , include('groups.urls')),
    url('^messages/' , include('vmessages.urls')),
    url('^notifications/' , include('notifications.urls')),
    url('^settings/' , include('settings.urls')),
    url('^signup/' , include('signup.urls')),
    url('^profile/' , include('uprofile.urls')),
]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

vmessages/urls.py
from django.conf.urls import url
from . import views

app_name = "messaging"


urlpatterns = [
    url('^$' , views.messaging , name = 'messaging'),
]

business/models.py
from django.db import models

# Create your models here.


class sell_goods(models.Model):
    itemid = models.AutoField(primary_key = True)
    itemdesc = models.CharField(max_length = 255 )
    price = models.FloatField(max_length = 10)
    itemimg = models.FileField()

home/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models

# Create your models here.
class signup(models.Model):
    pass

    class Meta:
        db_table = "signup"

business/forms.py
from django import forms
from .models import sell_goods

class sell_frm(forms.ModelForm):
    class Meta:
        model = sell_goods
        fields = ('itemdesc','price' , 'itemimg')

        widgets = {
            'itemdesc':forms.Textarea(attrs = {'rows':4 , 'cols':30 , 'name':'description'}),
        }

business/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import sell_frm



def business(request):
    form = sell_frm()
    if request.method =='POST':
        return render(request , "business/business.html" , context = {"form":form})

    else:
        return render(request , "business/business.html" , context = {"form":form})

discover/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.



def discover(request):
    return render(request , "discover/discover.html")

groups/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def groups(request):
    return HttpResponse("Hello groups")

home/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request , "home/home.html")

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.



def login(request):
    return render(request , "login/login.html")


def forgotcredetials(request):
    return render(request , "login/forgot.html")

settings/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.



def settings(request):
    return HttpResponse("Hello settings")

signup/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def signup(request):
    return render(request , "signup/signup.html")

uprofile/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def profile(request):
    return render(request , "uprofile/uprofile.html")

vmessages/views.py
from django.shortcuts import render

from django.http import HttpResponse
# Create your views here.


def messaging(request):
    # return HttpResponse("Hello messages")
    return render(request , "messages/messages.html" ,)

discover/templates/discover/discover.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      <link rel="icon" href="{% static 'business/img/vibes.jpg' %}" type="image/jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
     integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'discover/discover.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/brands.min.js">

  </script>
    <meta charset="utf-8">
    <title>Vibes | Discover</title>
  </head>
  <body>
    <div class="header">
      <div class="nav-bar">
        <div class="logo">
            <img src="{% static 'business/img/vibes.jpg' %}" alt="">
        </div>



            <a href="{% url 'profile:profile' %}">
              <span class="fa fa-home"></span>

            </a>


            <a href="{% url 'groups:groups' %}">
              <span class="fa fa-users"></span>

            </a>

            <a href="{% url 'messaging:messaging' %}">
              <span class="fa fa-envelope"></span>

            </a>


            <a href="{% url 'business:business' %}">
              <span class="fas fa-business-time"></span>
            </a>

      </div>
    </div>


    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-sm-8 col-md-8 col-lg-8 col-sm-8 search">
          <input type="search" name="search" placeholder="search">
        </div>


        <div class="col-xs-12 col-sm-12 col-sm-4 col-md-4 col-lg-4 col-xl-4 aroundyou">
          <label>Around you</label>
        </div>

      </div>
    </div>


    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-sm-7 col-md-7 col-lg-7 col-sm-7 search">

          <!-- card starts here -->

            <div class="singleuser">
              <h5 class="suggestuser">Name</h5>

              <div class="container">
                <div class="row">
                  <div class="col-xm-12 col-sm-12 col-lg-4 col-xl-4 profile">
                    <img src="{% static 'discover/img/robot.jpg' %}" class="card-img-top" alt="No image">
                  </div>
                  <div class="col-xm-12 col-sm-12 col-lg-8 col-xl-8 description">
                    <p>lorem</p>

                    <div class="follow">
                      <label><i class="fa fa-map-marker"></i>Location</label>
                      <label>Field</label>
                      <button type="button" name="button"><a href="#">Follow</a></button>
                    </div>

                  </div>

                </div>
              </div>

            </div>
          <!-- card ends here -->

        </div>


        <div class="col-xs-12 col-sm-12 col-sm-5 col-md-5 col-lg-5 col-xl-5">
            <div class="card">

              <!-- Loop through this div -->

              <div class="arounddescription">

                <div class="user-img">
                  <img src="{% static 'discover/img/robot.jpg' %}" alt="">
                </div>

                <div class="user-content">
                  <label>Name</label>
                  <label>Field</label>
                  <label>Location</label>
                  <button type="button" name="button">
                    <a href="#">Follow</a>
                  </button>
                </div>

              </div>

              <!-- End of individual dataset -->















            </div>
        </div>

      </div>
    </div>


  </body>
</html>

login/templates/login/forgot.html
{% load static %}
<!DOCTYPE html>
<html >

<head>
	<title>Vibes | Password recovery</title>
	<link rel="stylesheet" href="{% static 'login/style.css' %}"/>
</head>
<body>
	<div class="bon">
		<div class="bony">
			<form action="recovery.html">
			<h3>please Enter your Email address.</h3>

			<input type="email" placeholder="Email Address" required>
				<input type="submit" value="submit">
		</form>
		</div>
	</div>

</body>
</html>

login/templates/login/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="{% static 'login/style.css' %}">
<title>Vibes</title>
</head>
<body>
<div class="nav-bar">
	<a href="{% url 'profile:profile' %}" >Home</a>
	<a href="{% url 'business:business' %}" >Business</a>
	<a href="{% url 'discover:discover' %}" >Discover</a>
</div>

<div class="loginbox">
	<h4>vibes</h4>
	<h3>log in to vibes</h3>
		<form action="" method="POST">
			{% csrf_token %}

				<label for="email">Email</label>
				<input type="text/number" id="email" name='email' autofocus="true" autosave="true">
				<label for="password">password</label>
				<input type="password" name="password" id="password"><br>
				<input type="submit" name="submit" value="Log in"><br>
		</form>

	<a href="#">forgot password?</a>
	<label>sign up for vibes</label>
</div>
</body>
</html>

login/templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html >
<head>

	<title>Vibes | Login</title>
	<link rel="stylesheet" href="{% static 'login/styles.css' %}"/>
</head>

<body>
	<p>
		<img src="{% static 'home/images/logo.jpg' %}" alt="image" id="photo" vibes>

	</p>
	<div class="bon">
		<div class="bony">


	<form action="{% url 'login:login' %}">

		<h3> Login Here</h3>
		<input type="text" placeholder="username" id="username" required class="input">

		<input type="password" placeholder="password" id="password" required class="input">
		<p>
				<div class="keepme">
					<input type="checkbox" id="keepme">
					<label for="keepme">keep me signed in</label>
				</div>

			</p>
		<input type="submit" value="login" class="input">

		<div class=""  id="forgot">
			<a href="{% url 'login:forgot' %}">
					<b>forgot password?</b>
			</a>
		</div>

		<p style="text-align:center">
			<span>New member?</span>

			<a class="link" href="{% url 'signup:signup' %}">
				<b>Signup</b>
			</a>

		</p>
	</form>
	</div>
</div>

</body>
</html>

login/templates/login/loginl.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Null and void</title>
  </head>
  <body>

  </body>
</html>

login/templates/login/recovery.html
<html >

<head>
	<title>Account Recovery</title>
	<link rel="stylesheet" href="style.css"/>
</head>
<body>
	<div class="bon">
		<div class="bony">
			<form action="recovery.html">
			<h3>Email verification link has been send.</h3>
			<p style="text-align: center" >We have send  verification link on your email addree please confirm your email address and login in to your account</p>

		
				<p style="text-align:center">Go back to  <a class="link" href="login.html"> <p align="center"><i><b>Login Page</b></i></a></p>


			
				
			</p>
		</div></div>

</body>
</html>

login/templates/login/thanks.html
<html >
<head>
	<meta charset="	UTF-8">
	
	<link rel="stylesheet" href="style.css"/>
</head>

<body>
	<div class="bon">
		<div class="bony">
			<h4>Thankyou for creating an account</h4>
			<p style="text-align: ">
				We have send  a verification link via your Email Address please confirm.
			</p>
			<p style="text-align:center";>
				<a href="login.html"><i><b>Sign In Now</b></i></a>

				</p>

</body>
</html>

login/templates/login/welcome.html
<html 
<head>
	<title></title>
	<link rel="stylesheet" href="style.css"/>
</head>
<body>
	<div class="bon"><div class="bony">
		<h3>Successful loged in</h3>
		<h3>Welcome back to Your Acount</h3>


		<p style="text-align:right;">
			<a class="link" href="login.html"><b>Logout</b></a>
		

</body>
</html>

uprofile/templates/uprofile/uprofile.html
{% load static %}

<!-- The profile page -->
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
     integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'uprofile/css/style.css' %}">
    <title>Uprofile</title>
  </head>
  <body>
    <div class="nav">
      <div class="navbar">
        <div class="img-logo">

        </div>
      </div>
      <div class="navbar first">
        <input type="search" name="" value="" placeholder="search.." style="border-radius:50px;padding-left:10px;">
      </div>
      <a href="#">
        <div class="navbar">
          Home
        </div>
      </a>
      <a href="#">
        <div class="navbar">
          Groups
        </div>
      </a>
      <a href="#">
        <div class="navbar">
          Notification
        </div>
      </a>
      <a href="#">
        <div class="navbar">
          Business
        </div>
      </a>
    </div>
    <!-- content-->
    <div class="row profile">
      <div class="col-md-3 profile-section">
        <center>
        <div class="img-logo2"></div>
        <p>username</p>
        <h6 class="text-success">online</h6>
        <div class=""><br>
          <p><span>15 </span> Messages</p>
          <p> Downloads</p>
        </div>
        <center>
      </div>
      <div class="col-md-9">
        <center>
          <h4>Events</h4>
        </center>
        <hr>
        <center>
          <div class="template row">
            <div class=" col-md-4 video-section">

            </div>
            <div class="col-md-6">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
            </div>
          </div>
          <div class="template row">
            <div class=" col-md-4 video-section">

            </div>
            <div class="col-md-6">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
            </div>
          </div>
        </center>
      </div>
    </div>
  </body>
</html>